### ISSUE TITLE
Standard JSON path syntax

### ISSUE THREAD

**Issue by avram** [RedisLabsModules/rejson#1]
The docs note that ReJSON has its own path syntax (https://github.com/RedisLabsModules/rejson/blob/master/docs/path.md) because there is no existing standard -- yet there are two relevant JSON path definitions with meaningful adoption, [JSONPath](http://goessner.net/articles/JsonPath/) and [JMESPath](http://jmespath.org/).

It may be that both are more flexible than you want for ReJSON, but both have strong library support and have the benefit of not completely reinventing that wheel.

**Comment by avram** [comment]
The fact that there are two doesn't make them not standards.

Glad that you see the syntax as a subset of JSONPath, hopefully that will mean that as path expressions become more powerful, ReJSON will not have to have unnecessary innovation.

**Comment by dvirsky** [comment]
At first we thought of implementing JSONPath, but it was as you guessed, an overkill for what we needed, and I didn't find a C imlementation of it (there might be one, I just didn't find one. If you know of any, do link to them here). When we'll add indexing this will be way more relevant.

**Comment by avram** [comment]
I can't vouch for their appropriateness for ReJSON, but I found these in a cursory search:

* https://github.com/ebassi/json-glib/blob/master/json-glib/json-path.c
* https://github.com/arisi/c-json-path

I'm personally more a fan of JMESPath, but there doesn't appear to be C implementation at all; the closest would be [the Rust version](https://github.com/mtdowling/jmespath.rs) that could be the basis of a library with C bindings.

**Comment by dvirsky** [comment]
thanks!
