### ISSUE TITLE
A node client

### ISSUE THREAD

**Issue by evanhuang8** [RedisLabsModules/rejson#10]
I made this node.js wrapper around the commands to automatically do the parsing and etc, thought I would throw it there:

https://www.npmjs.com/package/iorejson

Helped me discover some bugs as well.

**Comment by itamarhaber** [comment]
You just made my day and relieved me of this dreaded task - I'm seriously grateful :medal_sports:

**Comment by evanhuang8** [comment]
Glad to help.

I hope to use this as a vehicle to do more edge case testing and load testing. Any feedback for the client is welcome as well!

**Comment by itamarhaber** [comment]
Added ioredis to the documentation - keep on finding my embarrassing bugs and the good work!
