### ISSUE TITLE
Non ascii in json keys

### ISSUE THREAD

**Issue by larswise** [RedisLabsModules/rejson#104]
Hi,

I'm having problems with non ascii characters in keys, more precisely when trying to access them:
Ø is encoded \u00c3\u0098
I stored this json using the StackExchange.Redis .net library.

redis 127.0.0.1:1337> json.get 3550:2018-12-20 .StopIndexes
"{\"GAR\":0,\"OSL\":1,\"NTH\":2,\"SK\\u00c3\\u0098\":3,\"LYS\":4,\"STB\":5}"

redis 127.0.0.1:1337> json.get 3550:2018-12-20 .StopIndexes"['STB']"
"5"

redis 127.0.0.1:1337> json.get 3550:2018-12-20 .StopIndexes"['SKØ']"
(error) ERR key 'SKØ' does not exist at level 1 in path

However, if I through redis-cli try to
json.set TESTP . '{"AØE": 100, "Stops": {"ÅBY": 1300}, "AAA": 200, "SKØ": 887}'

redis 127.0.0.1:1337> json.get TESTP
"{\"A\\u009dE\":100,\"Stops\":{\"\\u008fBY\":1300},\"AAA\":200,\"SK\\u009d\":887}"

redis 127.0.0.1:1337> json.get TESTP "['SKØ']"
"887"

It works. It also looks like there's a different encoding than what was stored using the library.

Any hints of solutions appreciated.
Thanks,
Lars

**Comment by larswise** [comment]
I got this working after some trial and error

**Comment by gkorland** [comment]
What was the issue?

**Comment by larswise** [comment]
Firstly, I thought I had it fixed, by doing some hackish character mapping, but I was wrong :) 

NB! I am using redis-py execute_command. I was (very positively) surprised to see that everything works as expected when using the rejson module. Guessing it has to be my workaround.

If you have any idea why Ø becomes \u00c3\u0098S through redis-py, but \u009d through both rejson-py and redis-cli I would highly appreciate it.

**Comment by larswise** [comment]
I belive there might be an issue here after all?
Please see: https://github.com/RedisLabs/rejson-py/issues/19

I did manage to get around it though:

In python I am able to restore the string by encoding as follows:
`somevalue.encode('utf-8').decode('unicode-escape').encode('latin1').decode('utf-8')`

and similarly in .NET after fetching with JSON.MGET

```
		public static string GetEncoded(params string[] strings)
		{
			var lat1 = System.Text.Encoding.GetEncoding("iso-8859-1");
			Regex rx = new Regex(@"\\[uU]([0-9A-Fa-f]{4})");
			var combined = string.Join(",", strings);
			var result = rx.Replace(combined, match => ((char)Int32.Parse(match.Value.Substring(2), System.Globalization.NumberStyles.HexNumber)).ToString());
			var lat1bytes = lat1.GetBytes(result);
			return System.Text.Encoding.UTF8.GetString(lat1bytes);
		}
```

**Comment by mschipperheyn** [comment]
Also having problems: https://github.com/RedisJSON/rejson-py/issues/19. I use node, but the problem occurs also using redis directly from the command line
