### ISSUE TITLE
[Crash] JSON.GET using the same path

### ISSUE THREAD

**Issue by alon-redis** [RedisLabsModules/rejson#13]
Redis server crashed when using the same path in rejson command. 
To reproduce:
```` 
172.31.21.227:11107> JSON.SET obj . '{"name":"Leonard Cohen","lastSeen":1478476800,"loggedOut": true}'
OK
172.31.21.227:11107> json.get obj . name . 
````

**Comment by itamarhaber** [comment]
@alon-redis thanks for finding and reporting!

Although this issue causes a crash, it isn't strictly urgent as it is triggered by misuse ;) Nonetheless, a fix should be put in place asap.
