### ISSUE TITLE
master-slave mode data inconsistency 

### ISSUE THREAD

**Issue by leonchen83** [RedisLabsModules/rejson#17]
run below command in master  
and data inconsistency in slave  

```java  
JSON.NUMINCRBY
JSON.ARRAPPEND
JSON.ARRINSERT
JSON.ARRTRIM
JSON.STRAPPEND
JSON.ARRPOP
```
but there are 2 commands data consistency in slave

```java  
JSON.SET
JSON.DEL
```

env

```
redis : redis-4.0-rc3
loaded module : both master and slave loaded rejson module
kernal : Linux version 4.8.13-100.fc23.x86_64 (mockbuild@bkernel02.phx2.fedoraproject.org) (gcc version 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC) )
```

**Comment by itamarhaber** [comment]
Thanks for reporting - I have a good notion of why this could be happening (i.e. my bug, my bad).

**Comment by leonchen83** [comment]
seems these commands miss `RedisModule_ReplicateVerbatim` or `RedisModule_Replicate`

**Comment by itamarhaber** [comment]
That's exactly the reason - I'd appreciate if you can verify that 8e11106 fixes this issue.

**Comment by leonchen83** [comment]
verified. could close this issue.

**Comment by itamarhaber** [comment]
@leonchen83 thanks!

It would be good to add master/slave (and perhaps cluster too) to https://github.com/RedisLabs/rmtest - @dvirsky wdut?
