### ISSUE TITLE
Standard JSON path

### ISSUE THREAD

**Issue by leonchen83** [RedisLabsModules/rejson#18]
this issue similar with [#1](https://github.com/RedisLabsModules/rejson/issues/1), but [RFC6901](https://tools.ietf.org/html/rfc6901) provide a simpler way to access json object.  
could this project support [that](https://tools.ietf.org/html/rfc6901) syntax?

**Comment by itamarhaber** [comment]
Isn't this issue a duplicate of #1?

**Comment by leonchen83** [comment]
yep ,but I saw [#1](https://github.com/RedisLabsModules/rejson/issues/1) has closed. so I opened this issue

**Comment by itamarhaber** [comment]
Sorry, I meant, isn't that #3?

**Comment by leonchen83** [comment]
yes ,pls close this issue

**Comment by itamarhaber** [comment]
Cool
