### ISSUE TITLE
Unable to execute execute the reJson Module in Mac

### ISSUE THREAD

**Issue by lakshmanraob** [RedisLabsModules/rejson#30]
Hi,
   I followed instructions given in http://rejson.io/#building-the-module for building the reJson library in MacOsX Machine. Post the git clone, i did not see src/make file to compile the module.
   I am using redis-4.0.0, and cloned the reJson Module from https://github.com/RedisLabsModules/rejson.git. The MacOS details were given below.

Mac OS version - MacOS Sierra 10.12.5

Thanks
Lakshman

**Comment by dvirsky** [comment]
Hi @lakshmanraob, the makefile you should run is not under src but in the root directory of the project. I have no problem running it in the same Mac OS version as yours. Do you have xCode installed? Or another version of make and gcc/clang?

**Comment by lakshmanraob** [comment]
hi @dvirsky ,
  Thanks for the support and quick response.  The OS and XCode update did the trick for me. I can able to install reJSON library on top of Redis 4.0.0.
