### ISSUE TITLE
Question: Can you timeout stored values somehow?

### ISSUE THREAD

**Issue by Sotorin** [RedisLabsModules/rejson#31]
Installation and compilation on Mac went without a hitch. It took me a while to figure out how to send commands from node_redis driver but I got that working too. So far, very pleased with this project.

Is there a way to timeout/expire or otherwise remove the value after certain amount of time?

`JSON.SET foo . '"bar"'` I would want this document to be purged after say 20 min.

**Comment by dvirsky** [comment]
You can use the normal EXPIRE redis command for that. You cannot expire parts of the document, just the entire thing. http://redis.io/commands/expire

_Sent from my OnePlus ONE A2001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Sotorin** [comment]
Yes, purging the document using `EXPIRE` works as expected.
`JSON.SET foo . '"bar"'` will create/set the document,
`EXPIRE foo 10` will purge the document after 10 seconds.

Thanks a lot!
