### ISSUE TITLE
Reconsider changing license from AGPL to more liberal one

### ISSUE THREAD

**Issue by manikantag** [RedisLabsModules/rejson#33]
Hi,

Thanks for the much needed module. I m interested in using this for one of the client project, but the AGPL license is stopping us. Any specific reason for AGPL? Can you consider it changing to at least LGPL if not more liberal one (like MIT, Apache, BSD, ..)? Thanks

**Comment by dvirsky** [comment]
@manikantag please read here about the reasons we are using AGPL for modules: https://redislabs.com/blog/why-redis-labs-modules-are-agpl/

Just to clarify - as long as you do not modify the module's own code or if you do change - contribute your changes back - you are safe. This is equivalent to using MongoDB. You application is not a derived work of the module. The license refers only to the module source code itself which is running inside redis. As long as you only interact with the module via its network API you have nothing to worry about.

**Comment by dvirsky** [comment]
Another note - we provide a commercial license as well as part of Redis Enterprise, if you *really* want to be on the safe side.

**Comment by manikantag** [comment]
@itamarhaber Continuing the Twitter DM conversation here, so that others also gets clarified.

Itamar Haber's Twitter DM reply:
> Hi manikanta - seen the issue in the repo and as @dvirsky answered... We are, in fact considering, adding a clause to the agpl that will make it more permissive. What are your concerns?

I'm not sure if I understood AGPL correct enough, but my understanding is we've to disclose source of our end product too. Wish I'm wrong :)

Some references I've found:

https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)


Github's help on project license: https://github.com/RedisLabsModules/rejson/blob/master/LICENSE
![image](https://user-images.githubusercontent.com/317299/29166043-93507562-7de2-11e7-92d0-755af3c048d8.png)



iText library license explanation doc (they clearly say, **the entire application source**): http://itextpdf.com/Pricing

> The iText AGPL license is for developers who wish to share their entire application source code with the open-source community as free software under the AGPL “copyleft” terms. As soon as you want to use iText in a closed source, proprietary environment, you have to purchase an iText commercial license of one of the types discussed above


MongoDB says the other thing: https://www.mongodb.com/blog/post/the-agpl

> Note however that it is NOT required that applications using mongo be published. The copyleft applies only to the mongod and mongos database programs. 


Metabse.com also says, it is not required: https://twitter.com/ManikantaG/status/684734174855475200
![image](https://user-images.githubusercontent.com/317299/29166641-dbbe9dcc-7de4-11e7-8356-2e4a065fd947.png)




And StackOverflow is full of mixed opinions: some say, AGPL or GPL doesn't talk about '**Combined Work**', but some say: '**Everything AGPL touches has to be AGPL**' :(

Hmmm... We could easily learn Tensorflow 👍   but, legal things are always complected... 👎

**Comment by dvirsky** [comment]
Interacting with a database that is AGPL does NOT affect your code. You are safe as long as you do not change the module source code. Most answers that say you are tainted refer to a **library** you link to your code, which the module is **not** from your POV: You are loading it into redis and then interacting with it via the network.

**Comment by manikantag** [comment]
Thanks @dvirsky for the clarification.

If I get it correctly, as **rejosn** will be loaded into Redis and app will interact with Redis using rejson commands. In this case it is safe to use as long as rejson is not modified. If rejson is modified, **only** rejson's modifications should be contributed, which is very much fine. We take some, we give some :)

But if we use an AGPL library (ex: jar) in our app, like iText, then we've to disclose entire app code, not just the modification we do for iText library. I m correct with this part?

Thanks for all your inputs.

**Comment by dvirsky** [comment]
Yes, this is the gist of it. Fear not!
