### ISSUE TITLE
JSONPath for array search

### ISSUE THREAD

**Issue by hiren-intellectdesign** [RedisLabsModules/rejson#38]
Raising here, as didn't know from where to get better support on documentation.

As part of evaluating ReJson for our project, trying to understand JSON Search capability with Array.

Tried following commands to create an Array:

```
JSON.SET acc_requests . '[]'
JSON.ARRAPPEND acc_requests . '{ "seqId" : "1", "accountId" : "ACCT_001", "balance" : 1001.1 }'
JSON.ARRAPPEND acc_requests . '{ "seqId" : "2", "accountId" : "ACCT_002", "balance" : 2002.2 }'
JSON.GET acc_requests .
```

Now I want to search for JSON document containing seqId as "2"

Tried using following syntax as per [JSONPath](http://goessner.net/articles/JsonPath/) syntax:

`
JSON.GET acc_requests '[?(@.seqId == "2")]'
`

But getting following error:

`
(error) ERR Search path error at offset 2: square brackets can only contain integers, single- or double-quoted strings
`

What am I doing wrong here? How can I access JSON document with search criteria?

**Also, how can I apply** AND / OR condition while searching document in an array?
For example, Getting a document that contains "seqId" = "2" OR "balance" > 1001

JSON Path documentation [here](http://rejson.io/path/) doesn't talk much about capabilities supported for now (or expected in future) and no examples too. Further clarity will be appreciated.

Thanks in advance!

**Comment by hiren-intellectdesign** [comment]
How do I show my keen interest in knowing answer for above problem? ;-)

**Comment by dvirsky** [comment]
@hiren-intellectdesign ReJSON Has no indexing, the path expressions are only used as accessors to document elements, not as selectors for searching documents.

**Comment by mnunberg** [comment]
I'm closing this, as we will never likely support this kind of searching in ReJSON. This *might* be something which could be added to [github.com/RedisLabsModules/RediSearch](RediSearch) though :)

**Comment by owexroasia** [comment]
@hiren-intellectdesign do you found a solution or alternative? I'm having the same problem

**Comment by gkorland** [comment]
@owexroasia you should check the RedisJSON (next gen) https://github.com/RedisJSON/RedisDoc/

**Comment by JoaoOxOc** [comment]
hi I'm already using redisjson v2. Is it possible to do a contains() or includes() in a json field? Already tried this syntax `"$.data[?(@.test[(@.contains('acc'))]` but it didn't work
