### ISSUE TITLE
ReJson first version

### ISSUE THREAD

**Issue by hiren-intellectdesign** [RedisLabsModules/rejson#39]
I understand current version is Beta quality (please correct, if that's not true).

What is the roadmap ahead? When do we expect first version, with production ready quality?

**Comment by dvirsky** [comment]
The module will be "officially released" in a few weeks, but that is not to say it's not stable right now. What you see now is what will be called 1.0.

**Comment by natoscott** [comment]
@dvirsky any specific date planned OOC?  I'd like to package this module for Fedora, and an official release is highly preferable to a github snapshot.  Thanks!

**Comment by dvirsky** [comment]
@natoscott I'll pack what we have no as RC this week, and if nothing arises we can call it 1.0 in a couple of weeks.

**Comment by dvirsky** [comment]
@natoscott are you adding other modules to fedora?

**Comment by natoscott** [comment]
@dvirsky thanks.  Yes, I've packaged several locally now, and will probably start the process of adding rebloom "officially" later this week, and then rejson once its released.

**Comment by dvirsky** [comment]
@natoscott cool. any chance you can add redisearch as well? it's the most popular and highly active one by far.

**Comment by natoscott** [comment]
@dvirsky yep, I have a spec file for redisearch too, but its a much more complex module & I figured I'd work up to that one.  :)  It also is in the not-quite-officially-released-yet category, I think.

cheers.

**Comment by dvirsky** [comment]
@natoscott we've released 0.99 today, on its way to become 1.0 within a few days.

**Comment by natoscott** [comment]
Great, thanks @dvirsky - I've started the Fedora package inclusion process
https://bugzilla.redhat.com/show_bug.cgi?id=1513293
(likewise for rebloom over in BZ 1513291)

**Comment by mnunberg** [comment]
We've released a 1.0 - I'm closing this for now.
