### ISSUE TITLE
[Crash] JSON.GET with empty key

### ISSUE THREAD

**Issue by merindorium** [RedisLabsModules/rejson#43]
Hi, I've found that empty path key crashes Redis server 
I think this issue is related with #13 
```
127.0.0.1:6379> JSON.SET foo . '{"bar":{"baz":42}}'
OK
127.0.0.1:6379> json.get foo .bar.
Could not connect to Redis at 127.0.0.1:6379: Connection refused

```
Crash report: [redis_error.log](https://github.com/RedisLabsModules/rejson/files/1441361/redis_error.log)

**Comment by dvirsky** [comment]
Thanks for this report. Fixed in master.
