### ISSUE TITLE
Can't send rejson commands via libhiredis

### ISSUE THREAD

**Issue by patilarpith** [RedisLabsModules/rejson#44]
I have libhiredis 0.13.3 installed on my local. All rejson commands send via redisCommand() results in error with message ```ERR JSON lexer error SPECIAL_EXPECTED at position 311``` 

redis-server version is 4.0.2 with rejson module pre-loaded.

I see that libhiredis is not listed under supported **Client libraries**. Is there a C, C++ client library that supports rejson?

**Comment by mnunberg** [comment]
This error means that there is something wrong with your JSON input. Can you provide a simple snippet of code which triggers this error?

**Comment by patilarpith** [comment]
I suspected that and played around with different JSON input values. Any JSON input value size was giving the same error.
Eg:
```
string key = "hash";
string path =  ".";
string payload = "{}";
auto ret = (redisReply *)redisCommand(m_connection, "JSON.SET %s %s '%s'", key.c_str(), path.c_str(), payload.c_str());
```

**Comment by mnunberg** [comment]
You need to remove the single quotes as they are not stripped by hiredis. i.e.

```
redisCommand(m_connection, "JSON.SET %s %s %s", key.c_str(), path.c_str(), payload.c_str());
```

**Comment by patilarpith** [comment]
That cleared it out. Thanks for the help. Closing the issue
