### ISSUE TITLE
ERR unknown command 'JSON.SET'

### ISSUE THREAD

**Issue by jeronimogdrone** [RedisLabsModules/rejson#45]
Installed both Redis and ReJson from source
Make install put redis-server and redis-cli in /usr/local/bin
copied the compiled rejson.so to /usr/local/lib
ran redis-server --loadmodule /usr/local/lib/rejson.so
it gave an error about missing redis-server so i added symbolic link in /usr/bin/redis-server

now when running redis-cli interactively trying out JSON.SET I get an error
looks like the module hasn't loaded ?
please help

**Comment by mnunberg** [comment]
`--loadmodule` needs to be supplied with every `redis-server` invocation. It sounds like you're under the impression that it's like an "install" command.

**Comment by limor1** [comment]
The logs don't indicated whether the module was successfully loaded
Is there a debug option to show that it was loaded?
Maybe a compile flag for the rejason that will cause it to print debug messages?

**Comment by itamarhaber** [comment]
Actually, the logs **do** show the module being loaded successfully:

```sh
$ redis-server --loadmodule ./src/rejson.so
...
              `-.__.-'

24443:M 24 Nov 19:32:42.913 # Server initialized
24443:M 24 Nov 19:32:42.913 # <ReJSON> JSON data type for Redis v0.99.1 [encver 0]
24443:M 24 Nov 19:32:42.913 * Module 'ReJSON' loaded from ./src/rejson.so
24443:M 24 Nov 19:32:42.914 * Ready to accept connections
```

**Comment by dvirsky** [comment]
@itamarhaber depending on the logging level they might not :)
However @limor1  the best way to tell if a module is loaded is to run `MODULE LIST`

**Comment by mnunberg** [comment]
Is this still an issue?

**Comment by dvirsky** [comment]
doesn't seem so

**Comment by jeronimogdrone** [comment]
@mnunberg @itamarhaber Thank you for your response. 
I solved it
