### ISSUE TITLE
Truncating doubles

### ISSUE THREAD

**Issue by tazimmerman** [RedisLabsModules/rejson#47]
Hi,

The documentation mentions numbers are stored as 64-bit integers or doubles. When I set a key as an array containing a large double, at a certain point it gets truncated. Hopefully I am doing something wrong.

```
127.0.0.1:6379> json.set test . '[999999999.987654321]'
OK
127.0.0.1:6379> json.get test .
[999999999.98765433]
```

So far, so good.

```
127.0.0.1:6379> json.set test . '[1512060373.222988]'
OK
127.0.0.1:6379> json.get test .
[1.512060e+09]
```

Uh-oh. I thought maybe this is just a display issue, so I queried the key with redis-py, but I get a different value than was I originally set.

```
In [59]: reply = redis.execute_command('json.get', 'test', '.')
In [60]: print(reply)
[1.512060e+09]
In [61]: json.loads(reply)
Out[61]: [1512060000.0]
```

Am I simply misunderstanding how things work here, or is there an issue? For the vast majority of the numbers I am storing, there have been no issues with precision, but in this case it's a UNIX timestamp which seems like a reasonable value to store.

Thank you for all your effort!

Troy

**Comment by mnunberg** [comment]
@dvirsky the library is storing it correctly, but isn't serializing it correctly. It seems the wrong printf formatting is being used. I see the code is trying to save space on the wire by using `%e` and/or `%g` in various places, but I'm unsure what the correct usage should be here.

**Comment by mnunberg** [comment]
This was a formatting issue on the part of ReJson. It should be fixed now.
