### ISSUE TITLE
AOF is not working when using LUA scripts with REJSON commands

### ISSUE THREAD

**Issue by idoko** [RedisLabsModules/rejson#49]
used docker file https://github.com/idoko/docker-rejson to create the setup.
```bash
docker run -v ~/Work/test_rejson:/data --name rj redis-json:latest
```

```bash
docker exec -it rj redis-cli
127.0.0.1:6379> json.set my_var "." '{"a":1}'
OK
127.0.0.1:6379> EVAL "redis.call('json.set', KEYS[1],'.',ARGV[1])" 1 'my_var' '{"b":2}'
"{\"b\":2}"
(nil)
127.0.0.1:6379> json.get my_var
"{\"b\":2}"
```
now after that i stop the container
```bash
docker stop rj
```
run it again
```bash
docker start rj
```

and now :
```bash
docker exec -it rj redis-cli
127.0.0.1:6379> json.get my_var
"{\"a\":1}"
```
which mean the AOF is not working when using lua scripts.
for me its critical issue since i'm looking for the persistence offered by AOF + I need the Atomic ability to get/set the data given by LUA script.

any idea how to solve the issue? any workaround?

**Comment by mnunberg** [comment]
What version of Redis are you using?

**Comment by idoko** [comment]
VERSION=4.0.2

**Comment by mnunberg** [comment]
Use 4.0.6

**Comment by dvirsky** [comment]
redis 4.0.0 to 4.0.5 contained serious replication bugs specifically manifested with Lua scripts and modules. as Mark wrote, try 4.0.6

**Comment by idoko** [comment]
@mnunberg @dvirsky Thanks!
with 4.0.6 its working
