### ISSUE TITLE
rejson.so on ubuntu Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by astutesoftware** [RedisLabsModules/rejson#54]
After running make the rejson.so is generated fine
However on including it in redis.conf, redis server does not start

[....] Starting redis-server (via systemctl): redis-server.serviceJob for redis-server.service failed because the control process exited with error code. See "systemctl status redis-server.service" and "journalctl -xe" for details.
 failed!

**Comment by dvirsky** [comment]
The error you're mentioning is unclear, it just says "look in the log for the actual error". 

But if it's 16.04 and you're using the redis provided by the system - of course it will not work, that's an old version that doesn't support modules. You need the latest version of redis (4.0.6) to be able to run. 

Let me recommend just running it in Docker, we have a ready image. But if not, there should be an apt repo with the latest version somewhere.

**Comment by astutesoftware** [comment]
Perfect. On building from source and using latest version it worked.
Thanks a bunch
