### ISSUE TITLE
incrementby not working as expected

### ISSUE THREAD

**Issue by astutesoftware** [RedisLabsModules/rejson#55]
The incrementby is not working as intended 
Please see the following.
I am trying to update a property called total_connected_users by 1 and this property belongs to a object called company. ie. company.total_connected_users
However the command returns a number that is incremented everytime i call it.
However the property of the object never changes.

192.168.1.13:0>JSON.NUMINCRBY  'company'  'total_connected_users'  1
"113"

192.168.1.13:0>JSON.GET 'company' .
"{"total_connected_users":102,"total_sites":46,"domains":{"tubely.com":{"site_id":1,"site_name":"Tubely","site_description":"Tubely - Webchat"},"jhoos.com":{"site_id":2,"site_name":"Jhoos","site_description":"Jhoos - Meet Singles across the world"},"livehealthclub.com":{"site_id":3,"site_name":"Live Health Club","site_description":"LHC- health chat"},"astute.ws":{"site_id":4,"site_name":"Astute","site_description":"Astute Developer Chat"}}}"

**Comment by mnunberg** [comment]
Seems like I'm not invalidating the cache in this case.

**Comment by itamarhaber** [comment]
@mnunberg thank goD it ain't a naming problem ;)

**Comment by astutesoftware** [comment]
Aha.. so when can we expect this to be nailed?
Thanks a bunch.

**Comment by itamarhaber** [comment]
@astutesoftware knowing how @mbusath operates, I'd say in 3... 2... 1...

**Comment by mnunberg** [comment]
Good thing I'm not M Busath.

**Comment by mnunberg** [comment]
https://github.com/RedisLabsModules/rejson/commit/8c6929dc209bc426bac1bc19051082cbf12e9f5e
