### ISSUE TITLE
setting a key with expires

### ISSUE THREAD

**Issue by astutesoftware** [RedisLabsModules/rejson#56]
The redis node syntax goes this way
client.set(key, value, 'EX', 60 * 60 * 24, callback);

and when i attempt with the json method, i get a  ERR wrong number of arguments for 'json.set' command

redis_client.json_set('company', 'total_sites', total_sites,'EX',10, function(e, obj) {
        if (e) {
            console.log("ERROR happened".red)
            console.log(e);
        } else {
            console.log("Updated Total Sites".green);
        }
    }); //update site count in redis

**Comment by dvirsky** [comment]
Hi @astutesoftware, the JSON module doesn't support the EX syntax, so naturally this fails. 
However you can expire a a JSON key by following the JSON.SET comand with an expire command. If atomicity is important, you can do that in a MULTI request. 

Not sure how it works with your client, but in general:

```
MULTI
JSON.SET foo ....
EXPIRE foo 60
EXEC
```

**Comment by Drau** [comment]
@dvirsky are there any plans for such a functionality?

**Comment by gkorland** [comment]
@Drau can you work with the solution @dvirsky suggested?
```
JSON.SET foo ....
EXPIRE foo 60
```

**Comment by Drau** [comment]
@gkorland , it is of course possible, I would just rather work only with the jsonset API provided by the package for the entire functionality :)

Would you take pull requests for this feature ?:)

**Comment by gkorland** [comment]
I'll be glad to take a PR, 
BTW, we are rewriting the module so it might be better to send the PR there https://github.com/RedisJSON/RedisDoc
