### ISSUE TITLE
Float Point Precision

### ISSUE THREAD

**Issue by evanhuang8** [RedisLabsModules/rejson#6]
AFAIK, float point in redis is stored as 64 bit ieee float, but when I try to retrieve a float point value stored in a JSON field, it seems to lose precision, or is automatically rounded:

```
127.0.0.1:6380[7]> json.set world . 1.33333333
OK
127.0.0.1:6380[7]> json.get world .
"1.33333"
127.0.0.1:6380[7]> set hello 1.33333333
OK
127.0.0.1:6380[7]> get hello
"1.33333333"
```

Is this expected behavior?

**Comment by dvirsky** [comment]
@itamarhaber I think it's a serialization issue, internally we shouldn't be losing precision

**Comment by evanhuang8** [comment]
@dvirsky I agree. The flag for serialization seems to be wrong at this line:

https://github.com/RedisLabsModules/rejson/blob/master/src/json_object.c#L342

I did some experiment for the flags:

(check out this snippet: https://repl.it/GjP1/0)

```c
#include <stdio.h>
#include <math.h>
#include <float.h>

int main ()
{
   float a = 1.333333;
  
   printf("Should be: %lf, but losing precision: %g", a, a);
   
   return(0);
}
```

Output of the above is:
```
Should be: 1.333333, but losing precision: 1.33333 
```

Supposedly `%g` outputs the shorter of `%e` or `%f`, which in this case it uses `%f` and loses precision. See a similar issue here:

https://github.com/json-c/json-c/pull/59

I get the need to save space for serialization, but in this case it should either do more detection in terms of precision or use `%e` outright.

**Comment by evanhuang8** [comment]
And changing `%e` to `%lf` fixes the problem:

```c
127.0.0.1:6380[7]> JSON.GET world
"1.333333"
```

Not sure about the implication in terms of the memory footprint, however.

**Comment by dvirsky** [comment]
It shouldn't matter in terms of memory since this is only done when serializing the objects. Maybe make a PR and we'll continue the discussion over there?

**Comment by evanhuang8** [comment]
Here you go.

**Comment by evanhuang8** [comment]
Apparently, `%.17g` is the more correct version:

http://stackoverflow.com/questions/16839658/printf-width-specifier-to-maintain-precision-of-floating-point-value
