### ISSUE TITLE
Build a include and expand feature into the ReJson module to fetch parts of large JSON documents

### ISSUE THREAD

**Issue by aniruddhadas** [RedisLabsModules/rejson#69]
Overview:
The spec is for building the include feature into the ReJson module.

Purpose:
	• This would reduce the amount of data transferred sent from redis.
	• This would push more computation into redis.

Description:
	• We have large documents in redis that we trim or expand certain attributes and send it out over the wire.  For e.g., 
		1. if you have a document in redis: key1: {'a':'1', 'b':'1', 'c':'1'}, if the user requests only for attribute 'a','c' for 'key1', the output from the module should be {'a':'1', 'c':'1'}.
	• We use Redis for storing very large json documents, we need this feature for pulling subparts of the document and this would cut down the amount of data transferred.  This would eliminate the need for having json parsing and composing on the service code.
	

Product Experience:

USE CASES:
	1. This feature will be very useful for retrieving parts of large json document in one redis call.
	
Product Support
We would like to measure the time difference between json parsing and json composition.

**Comment by mnunberg** [comment]
Hi. This sounds a lot like what this module does already. Can you please show an example of input/output that you've tried, and what kind of change you want to see in the current module, and why?

**Comment by aniruddhadas** [comment]
Hi.  The problem is rejson only pulls out one attribute, we store large json documents in redis.  We are looking for some way to pull out multiple parts from the json document in a single call. for e.g.:
 document in redis: key1: {'a':'1', 'b':'1', 'c':'1'}.  We want to pull out a and c from the document so something like
Input: JSON.GET key .a .c
Output: key1: {'a':'1', 'c':'1'}

**Comment by arpitmalhotra** [comment]
+1 This would be a really useful feature to have.

**Comment by aniruddhadas** [comment]
Thanks @itamarhaber!  This is awesome!  One quick questions, does this support multi level selects or index based selects?

JSON.SET key1 . '{"a":"1", "b":"1", "c":"{ \"x\":\"1\" }"}'
JSON.GET key1 a c.x?

We use jedis. I dont think Jedis supports this ReJson but we can work around it.

**Comment by aniruddhadas** [comment]
Thanks Kyle, Itamar and Mark for the quick feedback!  This is awesome! Adding documentation link here for completeness: https://github.com/RedisLabsModules/rejson/blob/master/docs/commands.md#jsonget

**Comment by itamarhaber** [comment]
@aniruddhadas the latest docs should also be always available online at https://oss.redislabs.com/rejson/commands/#jsonget

Happy hacking!
