### ISSUE TITLE
Mocking rejson

### ISSUE THREAD

**Issue by mfidemraizer** [RedisLabsModules/rejson#83]
Hey! 

Have you ever had to mock `rejson`?

I'm using [redis-mock](https://www.npmjs.com/package/redis-mock) but I'm stuck because I see that there's nothing about mocking `rejson`.

A possible approach to mock it would be using JSON path behind the scenes to store JSON in `Map` keys.

How do you mock Redis + rejson in your own infrastructure? Or, do you avoid mocking Redis at all because it's light enough?

**Comment by itamarhaber** [comment]
Hey @mfidemraizer 

We don't mock - we spin dispsoable ones, look into the rmtest class. Not perfect, but easy... 🤷‍♂️

**Comment by mfidemraizer** [comment]
@itamarhaber Thanks, I'll take a look tomorrow!

**Comment by kamiljano** [comment]
this is clearly not in place yet... after 2 years... Replacing this with 2 more clearer tickets:

* https://github.com/yeahoffline/redis-mock/issues/163
* https://github.com/yeahoffline/redis-mock/issues/164
