### ISSUE TITLE
Any problem using rejson in multiple clusters/ multiple nodes environment?

### ISSUE THREAD

**Issue by anh194** [RedisLabsModules/rejson#85]
Hi. Just installed rejson on top of redis. **I wonder, does rejson support cluster / multiple nodes?** I know redisearch does not support cluster mode unless you buy the enterprise version. Therefore I want to ask before deploy rejson into our production server. Thank you. 
Edit:
I also would like to ask, is there way to install rejson other than docker ?

**Comment by itamarhaber** [comment]
Hello @anh194 

> does rejson support cluster

Yes - ReJSON operations are scoped to explicit keys, so it is supported by the cluster without further effort (RediSearch, as you've mentioned, is available only commercially on a cluster where it employs additional components that are not part of Redis OSS).

There should be nothing preventing you from using ReJSON on the open source or commercial clusters, just make sure you comply with the module's license.

> I also would like to ask, is there way to install rejson other than docker ?

Sure - I install it by cloning this repo and running make :)

Closing this as a non-issue.
