### ISSUE TITLE
How can I expire some keys of a json obj?

### ISSUE THREAD

**Issue by tangkangrui** [RedisLabsModules/rejson#86]
In my ops system, users can obtain admin authority for 10mins，this is how I do it:

1. When user get admin authority, I do "JSON.SET auth '["$username"]["admin"]' 1".
2. Then, I would like to set this value to 0 again after 10 minutes, and it reminds me of "EXPIRE" command of redis.
3. Howerver, I find out that the "EXPIRE" command can only be used on keys, but I certainly don't want to delete the entire key "auth".

Any idea how I can solve this problem? 
Thanks a lot for your help.

**Comment by itamarhaber** [comment]
Hello @tangkangrui 

You are correct. Redis expires keys. ReJSON's documents are keys. ReJSON does not support (currently) expiration of elements inside a document.

That said, if all you care about is per user admin authentication for 10 minutes, you don't need to store it with ReJSON and can just:

```
SET auth:admin:$username 1 EX $ttl
```

So Redis will expire it. Does this make sense?

**Comment by tangkangrui** [comment]
@itamarhaber 
Your suggestion is helpful, thanks.
