### ISSUE TITLE
Case doubt: to locate some data into the JSON or to generate a proper data structure

### ISSUE THREAD

**Issue by mfidemraizer** [RedisLabsModules/rejson#89]
Say we've a key `school:teachers:11`. A teacher may look as follows:

```json
{ 
      "id": 28,
      "name": "John",
      "subjectId": 848
}
```

Now I want to get the `subject` given a `school`, so I should `get school:subjects:[id]`.

Usually I would create a Redis hash to map each association to its `id` in order to retreive entity's JSON: `hset school:teachers:subjects 28 848`, or I would create a string `set school:teachers:subjects:28 848`.

My doubt is that I could also access `subjectId` using `json.get school:teachers:28 .subjectId`, but I find that this is abusing Rejson, and, at the end of the day, `json.get` has `O(N)` time complexity, while `get` and `hget` have `O(1)`. 

What's your advise about this?

Thank you in advance.

**Comment by itamarhaber** [comment]
Hello @mfidemraizer 

In the case above, each `JSON.GET` is O(1) since the value you're getting is a single number (subjectId). That said, to fetch all subjects in a given school, you should explicitly index that (in a string, hash or another JSON document/sub-document) to have everything ready in one read.

In the future, ReJSON (or another module) will offer support for more sophisticated search patterns.

**Comment by mfidemraizer** [comment]
@itamarhaber Hey! ;-)

Anyway, I've not checked ReJSON's source code, but anyway, does it add any overhead in terms of deserialization? I'm concerned about `json.get x .y` vs `hget x y`.

Thanks again!

**Comment by mfidemraizer** [comment]
@itamarhaber Uhm, I've read that JSON is parsed and stored using a tree data structured, so I assume that the perf `get` vs `json.get` should be negligible, right?

**Comment by itamarhaber** [comment]
The performance of `JSON.GET` depends on the size of the returned value. The bigger it is, the more expensive it is to serialize to JSON from binary tree form. In the case of a single number being returned, it should be negligible but I urge you to actually test it :)

**Comment by mfidemraizer** [comment]
@itamarhaber I believe that I won't need to test the perf. The actual case I'm covering using `json.get` is always returning a number/uuid.  

That tree structure saves a lot of extra keys that I would have to create otherwise. It's ok!

Thank you for your advise!
