### ISSUE TITLE
Redis standalone mode and ReJSON module crashed

### ISSUE THREAD

**Issue by dotrungduchd** [RedisLabsModules/rejson#9]
Hi! I tested Redis standalone mode and ReJSON module today (git clone both) and Redis crashed. 
CPU: Intel® Core™ i5-6200U CPU @ 2.30GHz × 4, ubuntu 16.04 LTS 64 bit
Allocator: make MALLOC=jemalloc
make test: All tests passed without errors!
I tested memory pass twice (./redis-server --test-memory 4096) but it still crash when i try this command:

127.0.0.1:6379> JSON.SET num . 0
OK
127.0.0.1:6379> JSON.NUMINCRBY num . 1
"1"
127.0.0.1:6379> JSON.NUMINCRBY num . 1.5

=== REDIS BUG REPORT START: Cut & paste starting from here ===
4282:M 30 Mar 15:56:42.536 # Redis 999.999.999 crashed by signal: 11
4282:M 30 Mar 15:56:42.536 # Crashed running the instuction at: 0x7f8aa9ea8664
4282:M 30 Mar 15:56:42.536 # Accessing address: 0x1dcc84a15
4282:M 30 Mar 15:56:42.536 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/zserver/rejson/rejson/lib/rejson.so(+0x6664)[0x7f8aa9ea8664]

Backtrace:
./redis-server *:6379(logStackTrace+0x45)[0x463fe5]
./redis-server *:6379(sigsegvHandler+0xb9)[0x4647a9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f8aac0fb390]
/zserver/rejson/rejson/lib/rejson.so(+0x6664)[0x7f8aa9ea8664]
./redis-server *:6379(RedisModuleCommandDispatcher+0x4f)[0x48c40f]
./redis-server *:6379(call+0xa6)[0x4255d6]
./redis-server *:6379(processCommand+0x3a7)[0x425cd7]
./redis-server *:6379(processInputBuffer+0xfd)[0x4357fd]
./redis-server *:6379(aeProcessEvents+0x128)[0x41f548]
./redis-server *:6379(aeMain+0x2b)[0x41f8eb]
./redis-server *:6379(main+0x495)[0x41c6c5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f8aabd41830]
./redis-server *:6379(_start+0x29)[0x41c8e9]

------ INFO OUTPUT ------
# Server
redis_version:999.999.999
redis_git_sha1:94751543
redis_git_dirty:0
redis_build_id:58fc46a9a4c59ba6
redis_mode:standalone
os:Linux 4.4.0-70-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:5.4.0
process_id:4282
run_id:b891b4865e95bb6bb63477f9c802e5265e4d5ecd
tcp_port:6379
uptime_in_seconds:123
uptime_in_days:0
hz:10
lru_clock:14469194
executable:/zserver/redis/redis/src/./redis-server
config_file:

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:890748
used_memory_human:869.87K
used_memory_rss:4501504
used_memory_rss_human:4.29M
used_memory_peak:890748
used_memory_peak_human:869.87K
used_memory_peak_perc:100.16%
used_memory_overhead:884874
used_memory_startup:835116
used_memory_dataset:5874
used_memory_dataset_perc:10.56%
total_system_memory:8248623104
total_system_memory_human:7.68G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:5.05
mem_allocator:libc
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:1
rdb_bgsave_in_progress:0
rdb_last_save_time:1490864079
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1
total_commands_processed:11
instantaneous_ops_per_sec:0
total_net_input_bytes:465
total_net_output_bytes:1102793
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:4
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:805e5c6e38edf6ba6453d7f23881ce3d80817bd7
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.14
used_cpu_user:0.07
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_del:calls=1,usec=10,usec_per_call=10.00
cmdstat_command:calls=1,usec=1106,usec_per_call=1106.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=2,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=2 addr=127.0.0.1:50374 fd=6 name= age=96 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=json.numincrby

------ CURRENT CLIENT INFO ------
id=2 addr=127.0.0.1:50374 fd=6 name= age=96 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=json.numincrby
argv[0]: 'JSON.NUMINCRBY'
argv[1]: 'num'
argv[2]: '.'
argv[3]: '1.5'
4282:M 30 Mar 15:56:42.538 # key 'num' found in DB containing the following object:
4282:M 30 Mar 15:56:42.538 # Object type: 5
4282:M 30 Mar 15:56:42.538 # Object encoding: 0
4282:M 30 Mar 15:56:42.538 # Object refcount: 1

------ REGISTERS ------
4282:M 30 Mar 15:56:42.538 # 
RAX:00000001dcc84a05 RBX:00000000018a6bc8
RCX:000000000180c918 RDX:00000001dcc84a05
RDI:00007fffab333940 RSI:000000000180c918
RBP:00007fffab333980 RSP:00007fffab333860
R8 :000000000180c910 R9 :3332366436333037
R10:000000000180c900 R11:00007f8aabeb5390
R12:0000000000000000 R13:0000000000000000
R14:00054beedf3356eb R15:000000000000000f
RIP:00007f8aa9ea8664 EFL:0000000000010206
CSGSFS:0000000000000033
4282:M 30 Mar 15:56:42.538 # (00007fffab33386f) -> 00000000018a5ae8
4282:M 30 Mar 15:56:42.538 # (00007fffab33386e) -> 00000000018a5cf8
4282:M 30 Mar 15:56:42.538 # (00007fffab33386d) -> 00000000018a59d8
4282:M 30 Mar 15:56:42.538 # (00007fffab33386c) -> 00000000018a6b7b
4282:M 30 Mar 15:56:42.538 # (00007fffab33386b) -> 00000000018a5a68
4282:M 30 Mar 15:56:42.538 # (00007fffab33386a) -> 3ff0000000000000
4282:M 30 Mar 15:56:42.538 # (00007fffab333869) -> 00000000018a6bab
4282:M 30 Mar 15:56:42.538 # (00007fffab333868) -> 00007fffab3338cf
4282:M 30 Mar 15:56:42.539 # (00007fffab333867) -> ffff800054ccc731
4282:M 30 Mar 15:56:42.539 # (00007fffab333866) -> 0000000000000000
4282:M 30 Mar 15:56:42.539 # (00007fffab333865) -> 00000006ac0e4b70
4282:M 30 Mar 15:56:42.539 # (00007fffab333864) -> 00007f8aac0e4b38
4282:M 30 Mar 15:56:42.539 # (00007fffab333863) -> 00007fffab333990
4282:M 30 Mar 15:56:42.539 # (00007fffab333862) -> 00000000018a5cc8
4282:M 30 Mar 15:56:42.539 # (00007fffab333861) -> 00000004ac0e4b70
4282:M 30 Mar 15:56:42.539 # (00007fffab333860) -> 00007f8aac0e4b38

------ FAST MEMORY TEST ------
4282:M 30 Mar 15:56:42.539 # Bio thread for job type #0 terminated
4282:M 30 Mar 15:56:42.539 # Bio thread for job type #1 terminated
4282:M 30 Mar 15:56:42.539 # Bio thread for job type #2 terminated
*** Preparing to test memory region 6f9000 (90112 bytes)
*** Preparing to test memory region 1800000 (831488 bytes)
*** Preparing to test memory region 7f8aaa0c9000 (8388608 bytes)
*** Preparing to test memory region 7f8aaa8ca000 (8388608 bytes)
*** Preparing to test memory region 7f8aab0cb000 (8388608 bytes)
*** Preparing to test memory region 7f8aac0e6000 (16384 bytes)
*** Preparing to test memory region 7f8aac303000 (16384 bytes)
*** Preparing to test memory region 7f8aac9c1000 (344064 bytes)
*** Preparing to test memory region 7f8aaca37000 (8192 bytes)
*** Preparing to test memory region 7f8aaca3b000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: (null) (base: (nil))
Module: /zserver/rejson/rejson/lib/rejson.so (base 0x7f8aa9ea2000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=(nil) -D -b binary -m i386:x86-64 /tmp/dump.bin

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/antirez/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.

Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected> exit
[1]+  Segmentation fault      (core dumped) ./redis-server --loadmodule /zserver/rejson/rejson/lib/rejson.so

**Comment by itamarhaber** [comment]
Thanks for reporting this - will provide a fix shortly.

**Comment by dotrungduchd** [comment]
Awesome. Thank you <3
